name: 'Repo Releases'
description: 'A Github action to get the latest release of the repository.'
author: 'muchobien'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
    required: false
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
  excludes:
    description: 'Types of releases to exclude from the list. (pre-release|draft)'
    required: false

outputs:
  release:
    description: 'Latest release name'
  version:
    description: 'Latest release version'
  id:
    description: 'Latest release ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
